<h1 class="title">Welcome to Zend Skeleton</h1>

<?php if (! $this->zfcUserIdentity()): ?>
    <p>
        This is a live demo. Click the <a href="<?php echo $this->url('about') ?>">About</a> page for more information.
    </p>
    <p>
        If you have any problems, try <a href="<?php echo $this->url('reset-db') ?>">resetting the demo database</a> to its default state.
    </p>
<?php else: ?>
    <p>Hi <?php echo $this->zfcUserDisplayName(); ?>.</p>
<?php endif; ?>
